version: "3.9"

services:
  db:
    image: postgres:17
    container_name: chat-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - chat-db-data:/var/lib/postgresql/data
    networks:
      - chat-network

  app:
    build: .
    container_name: chat-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chatdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    ports:
      - "8080:8080"
    networks:
      - chat-network

volumes:
  chat-db-data:

networks:
  chat-network:
